### ISSUE TITLE
issue on backing on script

### ISSUE THREAD

**Issue by killmasta93** [sebastian13/lvm-restic-backup#3]
Hi,
Currently trying to backup LVM using the script, but currently getting this error

```
=======================================================
Starting backup of LV /dev/vg_data01

[Error] Cannot find path for /dev/vg_data01

 ___              ___  __  
|__   /\  | |    |__  |  \ 
|    /--\ | |___ |___ |__/ 

```

```
vgscan 
  Reading volume groups from cache.
  Found volume group "vg_log01" using metadata type lvm2
  Found volume group "vg_tempdb" using metadata type lvm2
  Found volume group "vg_data01" using metadata type lvm2

```

Not sure if the command im running is correct?

`lvm-rescript sql block-level-backup /dev/vg_data01/ `

**Comment by sebastian13** [comment]
Hi,

you must use a LV name, not a VG name/VG path. So in your case, the command could be similar to this:

`lvm-rescript sql block-level-backup lv01`
